### ISSUE TITLE
一直提示账号密码错误，但是是没有问题的

### ISSUE THREAD

**Issue by ylighgh** [trulymust/neteasy_music_sign#1]
![image](https://user-images.githubusercontent.com/59725600/169956350-ec85d9b8-24bc-493c-97c7-cfdf3351ebfd.png)
![image](https://user-images.githubusercontent.com/59725600/169956397-f992f43e-0af0-4112-a01d-2ebff614d1c2.png)

**Comment by ylighgh** [comment]
请问楼主这个应该怎么解决。api也是正常运行的

**Comment by ylighgh** [comment]
万分感谢

**Comment by trulymust** [comment]
你好，我这边测试大概率是账号密码问题，建议你尝试下修改密码后登录或者检查密码有没有输入错误
![image](https://user-images.githubusercontent.com/55483183/169958000-a758c105-7c3c-47d9-9f9b-53c14954dca0.png)
![image](https://user-images.githubusercontent.com/55483183/169958039-cba9e3ae-46be-4eeb-a368-2136197f9023.png)

**Comment by trulymust** [comment]
若修改密码后依然不能登录请继续与我联系，我会持续帮你解决

**Comment by ylighgh** [comment]
您好，原来我的API接口用错了，忘记改了，用了您的README的API就解决了
但现在又有一个新的BUG，我想多人升级，但是显示没有 `countrycode` 这个参数 但是 `account.json` 里面已经设置了的
![image](https://user-images.githubusercontent.com/59725600/169993338-cd827229-283e-4354-a85a-800379f1c67a.png)

![image](https://user-images.githubusercontent.com/59725600/169992964-da432f0a-9081-4587-8063-ce24222c78b3.png)

**Comment by trulymust** [comment]
不好意思，这个是我的疏忽，这个功能因为我当时没有多余账号就没有做测试，我这两天抽时间解决这个问题，请注意git更新。

**Comment by ylighgh** [comment]
幸苦了，谢谢你~

**Comment by trulymust** [comment]
多账号已经更新了，你可以帮我测试下了

**Comment by ylighgh** [comment]
好的，谢谢，辛苦了，下午测试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月25日(周三) 上午10:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [trulymust/neteasy_music_sign] 一直提示账号密码错误，但是是没有问题的 (Issue #1)




 
多账号已经更新了，你可以帮我测试下了
